import {projects,workflowSteps,knowledge} from './data.mjs';
import {state,selectCapabilities,selectProjects,catalogMetrics} from './state.mjs';
import {heading,button,badge,projectTable,capabilityTable,empty} from './components.mjs';
import {graph} from './graph.mjs';
import {trackingView} from './tracking-view.mjs';

const metric=(label,value,detail,accent='')=>`<article class="metric ${accent}"><span>${label}</span><strong>${value}</strong><small>${detail}</small></article>`;
const panelHead=(label,extra='')=>`<div class="panel-heading"><h2>${label}</h2>${extra}</div>`;
function attention(items){
 const signals=items.filter(i=>['Bloqueado','Desactualizado'].includes(i.state));
 return panelHead('Dónde mirar primero',`<span class="count-pill">${signals.length} ejemplos</span>`)+signals.map(i=>`<button class="attention-item" data-inspect="${i.id}"><span class="attention-icon ${i.state==='Bloqueado'?'rose':'amber'}">${i.state==='Bloqueado'?'!':'↻'}</span><div><b>${i.state==='Bloqueado'?'Una capacidad sin responsable':'Evidencia que necesita renovarse'}</b><p>${i.note}</p><small>${projects.find(p=>p.id===i.project).name.toUpperCase()} · EJEMPLO</small></div><span>↗</span></button>`).join('')+`<p class="annotation">${signals.length?'Casos ilustrativos, no incidencias detectadas.':'No hay señales de ejemplo en este filtro. No es una validación real.'}</p>`;
}
export function overview(){
 const items=selectCapabilities({...state,kind:'Todos'}),m=catalogMetrics(items),ps=selectProjects();
 return heading('TU SISTEMA, A LA VISTA','Menos puntos ciegos. Más contexto.','Comprende qué tienes, cómo se conecta y qué necesita tu atención.',button('Explorar capacidades ↗','catalog','primary'))+
 `<div class="metrics">${metric('PROYECTOS EN ESTA VISTA',ps.length,'Ejemplos, no inventario real')}${metric('CAPACIDADES DEFINIDAS',m.total,'Agents, skills y rules')}${metric('REQUIEREN ATENCIÓN',m.attention,'Señales sintéticas para revisar','attention')}${metric('OBSERVABILIDAD DE USO',`${m.measured} / ${m.total}`,'Capacidades con medición de ejemplo')}</div>
 <div class="overview-grid"><section class="panel projects-panel">${panelHead('Tus proyectos',button('Ver todos →','projects','text'))}${projectTable(ps)}<div class="panel-foot"><span class="tiny-dot"></span>La configuración no equivale a salud de ejecución.</div></section>
 <section class="panel attention-panel">${attention(items)}</section>
 <section class="panel map-panel">${panelHead('El mapa de tu ecosistema',button('Abrir mapa →','knowledge','text'))}<div class="panel-subtitle">Del proyecto a las capacidades que lo sostienen.</div>${graph()}</section>
 <section class="panel insight-panel"><p class="eyebrow">UNA PREGUNTA ÚTIL</p><h2>¿Lo tengo disponible<br>o lo estoy usando?</h2><p>Son dos cosas distintas. El catálogo muestra lo definido. La observación permite hablar de uso.</p><div class="insight-stat"><span>Uso no instrumentado</span><strong>Sin medir <span>○</span></strong></div><p class="annotation">No lo llamaremos «infrautilizado» sin una ventana de observación suficiente.</p>${button('Revisar catálogo →','catalog','secondary')}</section></div>`;
}
export function projectView(){return heading('CONTEXTO POR PROYECTO','Cada proyecto, en su contexto.','Responsables, capacidades y evidencia, sin mezclar contenido de otros espacios.')+`<section class="panel">${panelHead('Inventario de ejemplo')}${projectTable(selectProjects())}</section><section class="panel spaced">${panelHead('Capacidades del ámbito seleccionado')}${capabilityTable(selectCapabilities({...state,kind:'Todos'}))}</section>`;}
export function catalog(){return heading('AGENTS · SKILLS · RULES','Lo que tu sistema sabe hacer.','Una definición puede estar disponible sin tener evidencia reciente ni uso medido.')+`<div class="segmented" aria-label="Filtrar por tipo">${['Todos','Agent','Skill','Rule'].map(k=>`<button data-kind="${k}" aria-pressed="${state.kind===k}">${k==='Todos'?'Todo el catálogo':k+'s'}</button>`).join('')}</div><section class="panel">${panelHead('Catálogo de capacidades',`<span class="muted">${selectCapabilities().length} resultados de ejemplo</span>`)}${capabilityTable(selectCapabilities())}</section><div class="contract-note"><b>Cuatro preguntas, no un único semáforo.</b><span>¿Está configurado? · ¿Qué evidencia existe? · ¿Sigue vigente? · ¿Tenemos uso observado?</span></div>`;}
export function agentsView(){
 const agents=selectCapabilities({...state,kind:'Agent'});
 return heading('AGENTES · DEMO','Quién hace qué en el ejemplo.','Estos roles y proyectos son sintéticos; cambia a Local para ver el registro permitido.')+
 `<div class="local-agent-grid">${agents.map(agent=>`<article class="panel local-agent-card"><div class="panel-heading"><h2>${agent.name}</h2><span class="type-label">DEMO</span></div><p>${agent.note}</p><small>${projects.find(project=>project.id===agent.project)?.name||''} · EJEMPLO</small></article>`).join('')||empty('No hay agentes de ejemplo en este filtro.')}</div>`;
}
export function knowledgeView(){const mode=state.graphMode||'capability';return heading('RELACIONES CON SENTIDO','Explora las conexiones.','Empieza por un proyecto y amplía el contexto sólo cuando lo necesites.')+`<div class="graph-toolbar"><div class="segmented"><button data-graph="capability" aria-pressed="${mode==='capability'}">Capacidades</button><button data-graph="knowledge" aria-pressed="${mode==='knowledge'}">Conocimiento</button></div><label>Profundidad <select id="depth">${[1,2,3].map(n=>`<option ${n===state.depth?'selected':''} value="${n}">${n} ${n===1?'salto':'saltos'}</option>`).join('')}</select></label><div class="zoom-controls"><button data-zoom="-0.15" aria-label="Alejar grafo">−</button><span>${Math.round(state.zoom*100)}%</span><button data-zoom="0.15" aria-label="Acercar grafo">+</button></div></div><section class="panel">${panelHead(mode==='capability'?'Mapa de capacidades':'Pregunta → decisión → evidencia',badge('Sin verificar'))}${graph(mode)}</section><div class="contract-note"><b>${mode==='capability'?'Una relación declarada no demuestra ejecución.':'Una conexión no demuestra que una decisión sea correcta.'}</b><span>Selecciona un nodo en la lista para abrir su ficha. Dibujo SVG de demostración; motor de grafo pendiente de evaluación.</span></div>`;}
export function flows(){return heading('DEL PLAN A LA EVIDENCIA','El trabajo también tiene un mapa.','Secuencia ilustrativa. No hay agentes ejecutándose ni aprobaciones reales.')+`<section class="panel flow-panel">${panelHead('Revisar una nueva capacidad','<span class="type-label">SIMULACIÓN</span>')}<div class="flow-steps">${workflowSteps.map((s,i)=>`<button class="flow-step ${i===state.step?'active':''} ${i<state.step?'past':''}" data-step="${i}" aria-pressed="${i===state.step}"><span class="step-number">${i<state.step?'✓':String(i+1).padStart(2,'0')}</span><b>${s.name}</b><small>${s.role}</small></button>`).join('')}</div><div class="flow-description"><p class="eyebrow">PASO ${state.step+1} DE 5 · ${workflowSteps[state.step].role.toUpperCase()}</p><h2>${workflowSteps[state.step].name}</h2><p>${workflowSteps[state.step].detail}</p><button class="button primary" data-next>${state.step===4?'Reiniciar simulación ↺':'Simular siguiente paso →'}</button></div></section><div class="contract-note"><b>El control humano no es un botón decorativo.</b><span>En el producto, una aprobación requerirá permisos, una versión concreta y evidencia. Este prototipo no autoriza nada.</span></div>`;}
export function brain(){const ps=selectProjects();return heading('MEMORIA · SESIONES · GIT','Continuidad, incluso entre ramas.','El producto podrá relacionar sesiones y commits mediante referencias verificables.')+`<div class="metrics">${metric('BRAIN','Sin conectar','No se ha leído memoria local')}${metric('REPOSITORIOS','Sin conectar','No se ha ejecutado ningún comando Git')}${metric('COSTE','Desconocido','No se estiman USD desde créditos')}</div><section class="panel">${panelHead('Así se vería la trazabilidad','<span class="type-label">DATOS FICTICIOS</span>')}${ps.length?`<div class="trace-list">${ps.map((p,i)=>`<article class="trace-row"><span class="project-icon" style="--project-color:${p.color}">${p.name[0]}</span><div><b>${p.name}</b><small>Sesión demo-${i+1} · referencia sintética</small></div><code>feature/demo-${p.id}</code><span class="trace-arrow">→</span><code>commit ficticio</code>${badge(i===0?'Sin verificar':'Sin medir')}</article>`).join('')}</div>`:empty()}<div class="panel-foot">Metadatos mínimos · sin diffs, mensajes privados ni contenido de clientes</div></section><div class="contract-note"><b>Un commit no prueba despliegue, revisión ni tiempo trabajado.</b><span>Los directorios temporales y worktrees tendrán identidad explícita. Las referencias inaccesibles se mostrarán como desconocidas.</span></div>`;}
export function renderView(){
 if(state.scenario==='loading')return heading('ESTADO DE LECTURA','Preparando tu vista…','Simulación de carga: no hay ninguna petición en curso.')+`<div class="skeleton-grid" role="status" aria-label="Cargando demostración">${Array.from({length:6},()=>'<div class="skeleton"></div>').join('')}</div>`;
 if(state.scenario==='empty')return heading('SIN DATOS','Todavía no hay un snapshot.','Cuando exista una fuente autorizada, aparecerá aquí.')+empty('Este es el estado vacío de demostración. Vuelve al estado Normal para explorar la maqueta.');
 if(state.scenario==='error')return heading('ERROR DE LECTURA','No pudimos preparar esta vista.','Error simulado. No significa que el sistema o el proyecto hayan fallado.')+`<section class="error-state"><span>!</span><h2>La fuente de ejemplo no está disponible</h2><p>Conservaremos la distinción entre un error de lectura y una comprobación fallida.</p><button class="button primary" data-retry>Reintentar demo</button></section>`;
 const stale=state.scenario==='stale'?'<div class="stale-banner">↻ <b>Snapshot antiguo de ejemplo.</b> Esta vista no describe necesariamente el estado actual.</div>':'';
 return stale+({overview,projects:projectView,tracking:trackingView,agents:agentsView,catalog,knowledge:knowledgeView,flows,brain}[state.route]||overview)();
}
